modules/manager/controllers/ProductController.php
<?php

namespace app\modules\manager\controllers;

use app\models\Photos;
use Yii;
use app\models\Product;
use app\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\GloblaComponent;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public $layout = 'main';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $photos = new Photos();
        if ($photos->load(Yii::$app->request->post())) {
            $photos->name = $photos->upload($photos, 'name');
            $photos->product_id = $id;
            $photos->save();
            return $this->redirect(['view', 'id' => $id]);
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
                'photos' => $photos
            ]);
        }
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionStatusUse($id, $page)
    {
        $photos = Photos::findOne($id);
        $photos->status_use = 1;
        $photos->save();
        foreach (Photos::findAll(['product_id' => $photos->product_id]) as $item) {
            if ($item->id != $id) {
                $ph = Photos::findOne($item->id);
                $ph->status_use = null;
                $ph->save();
            }
        }
        return $this->redirect(['product/view', 'id' => $page]);
    }

    public function actionDeletePhotos($id, $page)
    {
        $photos = Photos::findOne($id);
        $photos->delete();
        unlink($photos->getUploadPath() . $photos->name);
        return $this->redirect(['product/view', 'id' => $page]);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/manager/views/product/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Types;
use dosamigos\ckeditor\CKEditor;
?>

<div class="product-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?php
    echo $form->field($model, 'types_id')->widget(\kartik\select2\Select2::classname(), [
        'data' =>ArrayHelper::map(Types::find()->where(['status'=>1])->all(),'id','name'),
        'options' => ['placeholder' => 'เลือกประเภทสินค้า ...'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

    <?= $form->field($model, 'price')->textInput() ?>


    <?= $form->field($model, 'details')->textarea(['rows' => '6']) ?>



    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/manager/views/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'types_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'details') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/manager/views/product/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = 'สร้างข้อมูลสินค้า';
$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลสินค้า', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-create">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/manager/views/product/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ข้อมูลสินค้า';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-index">
    <?php

    ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('สร้างข้อมูลสินค้า', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            'name',
            'typesName',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return Yii::$app->global->status($model->status);
                }
            ],
            'sumAmount',
            'price',
            //'details',
            //'created_by',
            //'updated_by',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

modules/manager/views/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = 'แก้ไขข้อมูลสินค้า: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลสินค้า', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="product-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/manager/views/product/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\file\FileInput;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="product-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="text-right">
        <?= Html::a('หน้าหลัก', ['index', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </div>
    <div class="row">
        <div class="col-md-8">
            <code>
                ขนาดรูปภาพ ต้องการ 600 x 600
            </code>
            <?php $form = ActiveForm::begin([
                'options' => ['enctype' => 'multipart/form-data']
            ]); ?>
            <?php
            //        echo '<label class="control-label">Upload รูปภาพสินค้า</label>';
            echo FileInput::widget([
                'name' => 'photos',
                'model' => $photos,
                'attribute' => 'name',
            ]);
            ?>
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
//            'id',
                    'name',
                    'typesName',
                    [
                        'attribute' => 'status',
                        'value' => function ($model) {
                            return Yii::$app->global->status($model->status);
                        }
                    ],
                    'sumAmount',
                    'price',
                    'details',
//            'created_by',
//            'updated_by',
                    'created_at',
                    'updated_at',
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">

        <?php foreach (\app\models\Photos::find()->where(['product_id' => $model->id])->orderBy('status_use' )->all() as $ps): ?>
            <div class="col-md-3">
                <div class="x_panel">
                    <div class="x_content">
                        <img class="img-responsive avatar-view" height="100%"
                             src="<?php echo Yii::getAlias('@web') . '/uploads/' . $ps->name ?>" alt="Avatar" title="">

                        <div class="text-right">
                            <?php   if($ps->status_use !=1):?>
                            <a href="<?= \yii\helpers\Url::to(['product/status-use', 'id' => $ps->id, 'page' => $model->id]) ?>"
                               class="btn btn-success"><i class="fa fa-check-circle-o"></i></a>
                            <a href="<?= \yii\helpers\Url::to(['product/delete-photos', 'id' => $ps->id, 'page' => $model->id]) ?>"
                               class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                            <?php else:?>
                                <a href="#" disabled
                                   class="btn btn-danger"><i class="fa fa-trash-o"></i></a>
                            <?php endif;?>

                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

</div>