models/MateOrder.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mate_order".
 *
 * @property int $id รหัสสั่งทำสินค้า
 * @property string|null $name ชื่อสั่งทำสินค้า
 * @property string|null $details รายละเอียด
 * @property int|null $user_id รหัสสมาชิก
 * @property int|null $deposit_price ราคามัดจำ
 * @property int|null $price ราคาเต็ม
 * @property string|null $time_length ระยะเวลา
 * @property int|null $status สถานะ
 * @property string|null $created_at วันที่สร้าง
 * @property string|null $updated_at วันที่แก้ไข
 */
class MateOrder extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mate_order';
    }
    public  $member_code;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    public function rules()
    {
        return [
            [['details'], 'string'],
            [['user_id', 'deposit_price', 'price', 'status'], 'default', 'value' => null],
            [['user_id', 'deposit_price', 'price', 'status'], 'integer'],
            [['created_at', 'updated_at','member_code'], 'safe'],
            [['name', 'time_length'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'รหัสสั่งทำสินค้า',
            'name' => 'ชื่อรายสั่งทำสินค้า',
            'details' => 'รายละเอียด',
            'user_id' => 'รหัสสมาชิก',
            'deposit_price' => 'ราคามัดจำ',
            'price' => 'ราคาเต็ม',
            'time_length' => 'ระยะเวลา',
            'status' => 'สถานะ',
            'member_code'=>'รหัสสมาชิก',
            'created_at' => 'วันที่สร้าง',
            'updated_at' => 'วันที่แก้ไข',
            'profileName'=>'ข้อมูลสมาชิก',
            'userCode'=>'รหัสสมาชิก',
             'statusName'=>'สถานะ'
        ];
    }

    public function getProfileName()
    {
        return Profile::findOne(['user_id'=>$this->user_id])->full_name;
    }
    public function getUserCode()
    {
        return Profile::findOne(['user_id'=>$this->user_id])->member_code;
    }

    public static function itemsAlias($key){

        $items = [
            'status'=>[
                1 => '<span class="label label-danger">รอจ่ายมัดจำ</span>',
                2 => '<span class="label label-success">รอตรวจสอบ..</span>',
                3 => '<span class="label label-success">จ่ายมัดจำแล้ว..</span>',
                4 => '<span class="label label-info">กำลังดำเนินการ...</span>',
                5 => '<span class="label label-warning">กำลังจัดส่ง...</span>.',
                6 => '<span class="label label-success">จัดส่งสำเร็จ...</span>.',
            ]
        ];
        return ArrayHelper::getValue($items,$key,[]);
    }
    public function getItemStatus()
    {
        return self::itemsAlias('status');
    }
    public function getStatusName(){
        return ArrayHelper::getValue($this->getItemStatus(),$this->status);
    }
}

controllers/MateOrderController.php
<?php

namespace app\controllers;

use app\models\MateOrder;
use app\models\Payment;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class MateOrderController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout',  'index'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionView($id)
    {
        $model = $this->findModel($id);
        return $this->render('view',['model'=>$model]);
    }
    public function actionSavePayment()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if($post = \Yii::$app->request->post()){
            $data = $post['item'];
             $model = $this->findModel($data['mate_order_id']);
            $payment = $post['item']['payment'];

            $sPayment = new Payment();
            $sPayment->status = 1;
            $sPayment->mate_order_id = $model->id; // รหัสสั่งทำ
            $sPayment->type_payment = 2;  // ประเภทสั่งทำ
            $sPayment->bank_id = intval($post['item']['bank_id']);
            $sPayment->check_time = $payment['hours'] . ':' . $payment['time'];
            $sPayment->remark = $payment['remark'];
            $sPayment->save();
            $model->status = 2;
            $model->save();

            $message = "\n " . ' ทำการชำระมัดจำสินค้าแล้ว';
            $message .= "\n ช่วงเวลา " . $payment['hours'] . ':' . $payment['time'];
            $message .= "\n ราคามัดจำ " . $model->deposit_price . ' บาท';
            $message .= "\n ตรวจรายการ " . 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . '/mate-order/confirm?id=' . $model->id;
            \Yii::$app->global->actionSendLine($message);
          return [
              'data' => 'ok'
          ];

        }else{
            return [
                'data' => 'not'
            ];
        }
    }
    public function actionConfirm($id){
        $model = $this->findModel($id);
        $model->status = 3 ;
        $model->save();
        $p = Payment::findOne(['mate_order_id'=>$model->id]);
        $p->status = 2;
        $p->save();
        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = MateOrder::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/mate-order/index.php
<?php

use yii\helpers\Html;

$this->title = 'สั่งทำสินค้า';
?>
<?= Yii::$app->global->breadcrumbDisplay($this->title) ?>
<br>
<div class="row">
    <div class="col-md-9">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#index">สั่งทำสินค้า</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#history">ประวัติสั่งทำ</a>
            </li>

        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane  active" id="index">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">รายการสั่งทำ <h4> รหัสสมาชิกของท่าน <strong
                                        class="text-danger"><?= @\app\models\Profile::findOne(['user_id' => Yii::$app->user->id])->member_code ?></strong>
                            </h4></h2>
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            <strong> <i class="fa fa-info-circle"></i> จะสั่งทำสินค้า กรุณา</strong> <span
                                    class="text-success"> @ไลน์ </span><span
                                    class="text-danger">หรือโทรสอบถาม</span> และแจ้งรหัสสมาชิกเพิ่มทำรายการ...
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="col-md-9">

                            <?php
                            $user_id = Yii::$app->user->id;
                            foreach (\app\models\MateOrder::find()->where("status!=6 and user_id = $user_id")->orderBy([
                                'status' => SORT_ASC,
                                'id' => SORT_DESC

                            ])->all() as $mo):?>
                                <div class="card text-left">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <p>ชื่อรายการ</p>
                                                <h4 class="card-title"><?= @$mo->name ?></h4>
                                                <p class="card-text"><?= @$mo->details ?></p>
                                            </div>
                                            <div class="col-md-5">
                                                <div class="pull-right text-right">
                                                    <h4 class="text-secondary">
                                                        ราคาเต็ม <?= number_format($mo->price, 0) ?>
                                                        บาท</h4>
                                                    <p class="text-secondary">
                                                        ราคามัดจำ <?= number_format($mo->deposit_price, 0) ?>
                                                        บาท</p>
                                                    <?php if ($mo->status == 1): ?>
                                                        <a href="<?= \yii\helpers\Url::to(['mate-order/view', 'id' => $mo->id]) ?>"
                                                           class="btn btn-outline-warning">โอนมัดจำ <strong
                                                                    class="text-danger">(<?= @number_format($mo->deposit_price, 0) ?>
                                                                บาท)</strong></a>
                                                    <?php elseif ($mo->status != 1): ?>
                                                        <button class="btn btn-outline-success">โอนมัดจำแล้ว
                                                            <?php if ($mo->status == 2): ?>
                                                                <strong class="text-warning">(รอตรวจสอบ...)</strong>
                                                            <?php elseif ($mo->status == 3): ?>
                                                                <strong class="text-danger">(ตรวจสอบแล้ว...)</strong>
                                                            <?php elseif ($mo->status == 4): ?>
                                                                <strong class="text-danger">(กำลังดำเนินการ...)</strong>
                                                            <?php elseif ($mo->status == 5): ?>
                                                                <strong class="text-danger">(กำลังจัดส่ง...)</strong>
                                                            <?php elseif ($mo->status == 6): ?>
                                                                <strong class="text-danger">(จัดส่งสำเร็จ)</strong>
                                                            <?php endif; ?>
                                                        </button>
                                                    <?php endif; ?>
                                                    <p> ระยะเวลา <?= @$mo->time_length ?></p>
                                                </div>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane  fade" id="history">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">ประวัติสั่งทำ <h4> รหัสสมาชิกของท่าน <strong
                                        class="text-danger"><?= @\app\models\Profile::findOne(['user_id' => Yii::$app->user->id])->member_code ?></strong>
                            </h4></h2>
                        <div class="col-md-9">
                            <?php
                            $user_id = Yii::$app->user->id;
                            foreach (\app\models\MateOrder::find()->where("status=6 and user_id = $user_id")->orderBy([
                                'status' => SORT_ASC,
                                'id' => SORT_DESC
                            ])->all() as $mo):?>
                                <div class="card text-left">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <p>ชื่อรายการ</p>
                                                <h4 class="card-title"><?= @$mo->name ?></h4>
                                                <p class="card-text"><?= @$mo->details ?></p>
                                            </div>
                                            <div class="col-md-5">
                                                <div class="pull-right text-right">
                                                    <h4 class="text-secondary">
                                                        ราคาเต็ม <?= number_format($mo->price, 0) ?>
                                                        บาท</h4>
                                                    <p class="text-secondary">
                                                        ราคามัดจำ <?= number_format($mo->deposit_price, 0) ?>
                                                        บาท</p>
                                                    <?php if ($mo->status == 1): ?>
                                                        <a href="<?= \yii\helpers\Url::to(['mate-order/view', 'id' => $mo->id]) ?>"
                                                           class="btn btn-outline-warning">โอนมัดจำ <strong
                                                                    class="text-danger">(<?= @number_format($mo->deposit_price, 0) ?>
                                                                บาท)</strong></a>
                                                    <?php elseif ($mo->status != 1): ?>
                                                        <button class="btn btn-success">โอนมัดจำแล้ว

                                                            <?php if ($mo->status == 6): ?>
                                                                <strong class="text-danger">(จัดส่งสำเร็จ...)</strong>
                                                            <?php endif; ?>
                                                        </button>
                                                    <?php endif; ?>
                                                    <p> ระยะเวลา <?= @$mo->time_length ?></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3 ">
        <h4 class=""> ติดต่อสอบถามสั่งทำและราคา</h4>
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="<?= Yii::getAlias('@web/app_frontend/images/line/10241.jpg') ?>"
                 alt="Card image cap">
            <div class="card-body">
                <a href="https://line.me/ti/p/Q_4rGTsu8j" class="btn btn-outline-success btn-block">@สอบถามและพูดคุย</a>
                <a href="084-5585-482" class="btn btn-outline-warning btn-block"><i class="fa fa-phone"></i>
                    084-5585-482</a>
            </div>
        </div>
    </div>
</div>

views/mate-order/view.php
<?php

use yii\helpers\Html;

$this->title = 'จ่ายสั่งทำสินค้า';
?>
<?= Yii::$app->global->breadcrumbDisplay($this->title) ?>
<div class="container" id="mete_order">
    <br>
<div class="row">
    <div class="col-md-5">
        <div class="card border-primary">
            <div class="card-body">
                <h3 class="card-text">รหัสสั่งทำ <?=@$model->id?></h3>
                <h5 class="card-title"><?=@$model->name?></h5>
                <p class="card-text"><?=@$model->details?></p>
                <p class="card-text">ระยะเวลา <?=@$model->time_length?></p>
                <p class="card-text">ราคามัดจำ <?=@number_format($model->deposit_price,0)?> บาท</p>
                <p class="card-text">ราคา <?=@number_format($model->price,0)?> บาท</p>
            </div>
        </div>
    </div>
    <div class="col-md-7" >
        <div class="card" v-if="!select_bank">
            <div class="card-body border-top">
                <h4>วิธีการชำระเงิน</h4>

                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#home">โอนธนาคาร</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#menu1">โอนพร้อมเพย์</a>
                    </li>

                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane container active" id="home">
                        <br>
                        <div class="row">
                            <div class="col-md-2">
                                <label>เลือกธนาคาร</label>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    <div class="col" v-for="bk in bank">
                                        <input type="radio" :id="bk.id" :value="bk.id" v-model="bank_id">
                                        <label :for="bk.id">{{bk.bank_name}}</label>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <table class="table table-md table-striped table-inverse table-responsive  mb-4  "
                               width="100%">
                            <thead class="thead-inverse" v-for="model in findBank">
                            <tr>
                                <th>ธนาคาร</th>
                                <th colspan="2">{{model.bank_name}}</th>
                            </tr>
                            <tr>
                                <th>ชื่อบัญชื่</th>
                                <th colspan="2">{{model.name}}</th>
                            </tr>
                            <tr>
                                <th>เลขที่บัญชี</th>
                                <th colspan="2">{{model.number_bank}}</th>
                            </tr>
                            <tr>
                                <th>จำนวนเงินที่ต้องโอน</th>
                                <th><strong class="text-danger "><?=number_format($model->deposit_price,0)?></strong> บาท</th>
                            </tr>
                            </thead>
                        </table>
                        <br>
                        <div class="text-right">
                            <button class="btn btn-outline-success text-right" :disabled="bank_id==null"
                                    @click="handlePay"> ยืนยัน
                            </button>
                        </div>
                    </div>
                    <div class="tab-pane container fade" id="menu1">
                        <br>
                        <div class="row">
                            <div class="col-md-2">
                                <label>เลือก</label>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    <div class="col" v-for="bk in bankPay">
                                        <input type="radio" :id="bk.id" :value="bk.id" v-model="bank_id">
                                        <label :for="bk.id"> {{bk.name}} ( {{bk.number_bank}} ) </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="text-right">
                            <button class="btn btn-outline-success text-right" :disabled="bank_id==null"
                                    @click="handlePay"> ยืนยัน
                            </button>
                        </div>
                    </div>
                </div>
            </div> <!-- card-body.// -->
        </div>
        <div class="card  mb-4" v-if="select_bank">
            <div class="card-body">
                <div class="text-center">
                    <h6 class="text-primary">ระยะเวลาในการโอน 10 นาที</h6>
                    <h1 class="text-danger display-4">{{time}}</h1>
                </div>
                <hr>
                <label>จำนวนเงินมัดจำ</label>
                <input value="<?=$model->deposit_price?>" class="form-control" disabled>
                <hr>
                <div class="row">
                    <div class="col-6">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <button class="btn btn-outline-secondary btn-sm" type="button"><i
                                            class="fa fa-clock"></i></button>
                            </div>
                            <select class="custom-select" v-model="payment.hours">
                                <option selected>เลือกชั่วโมง...</option>
                                <option :value="hr.hours" v-for="hr in hoursArray">{{hr.hours}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <button class="btn btn-outline-secondary btn-sm" type="button"><i
                                            class="fa fa-clock"></i></button>
                            </div>
                            <select class="custom-select" :disabled="payment.hours==null"
                                    v-model="payment.time">
                                <option selected>เลือกนาที...</option>
                                <option :value="mt.time" v-for="mt in minutesArray">{{mt.time}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12">
                                    <textarea class="form-control" rows="3" placeholder="หมายเหตุ"
                                              v-model="payment.remark">
                                    </textarea>
                    </div>
                </div>
                <hr>
                <button class="btn btn-success btn-block" @click="saveMateOrder" :disabled="check_btn(payment)">
                    ยืนยันการชำระ
                </button>
            </div> <!-- card-body.// -->
        </div> <!-- card.// -->
    </div>
</div>
</div>
<?php
$bank = \yii\helpers\Json::encode(\app\models\BankPayment::find()->where(['bank_type' => 1])->all());
$bankPay = \yii\helpers\Json::encode(\app\models\BankPayment::find()->where(['bank_type' => 2])->all());
$this->registerJs('
let app_cart_list = new Vue({
    el:"#mete_order",
    store,
    data:{
        bank_id:null,
        select_bank:false,
        payment:{
            hours:null,
            time:null,
            remark:null
        },
        date: moment(60 * 10 * 1000),
        bank:' . $bank . ',
        bankPay:' . $bankPay . ',
        minutes:[],
        hours:[]
    },
    mounted(){
       for(var h=1; h <=  24 ;h++){
        let jsonH = {}
        jsonH ={
            hours : h
        }
             this.hours.push(jsonH)
        }
      
        for(var i =1 ; i< 60 ;i++){
        let json ={
            time: i
        }
            this.minutes.push(json)
        }
    },
    computed:{
    minutesArray(){
        var d = new Date();
        var m = d.getMinutes();
        return this.minutes.filter(item=>item.time > m-3)
    },
     hoursArray(){
        var d = new Date();
        var h = d.getHours();
       return  this.hours.filter((item)=>{
         if(item.hours > h-2){
            if(item.hours ==24) { item.hours ="00"}
            return item
          }
         })
    },
     time: function(){
      return this.date.format(\'mm:ss\');
    },
    findBank(){
        return this.bank.filter(item=>item.id == this.bank_id);
    }
    
    },
    methods: {
       saveMateOrder(){
         let item ={
            payment:this.payment,
            bank_id:this.bank_id,
            mate_order_id:'.$model->id.'
        }
          return  jQuery.post("/mate-order/save-payment",{item,_csrf: csrfToken},function(res){
        console.log(res)
        if(res.data == "ok"){
        Swal.fire({
            type: "success",
            title: "ชำระมัดจำสำเร็จ !",
            showConfirmButton: false,
            timer: 5000
          })
         window.location.href="/mate-order/index";
        }
         })
       },
       check_btn(item){
            if(item.hours && item.time){
                return false;
            }else{
                return true;
            }
       },
       handlePay(){
     this.select_bank = true;
     let interval = setInterval(() => {
        let date  = moment(this.date.subtract(1, \'seconds\'))
         let time = date.format(\'mm:ss\');
          this.date = moment(this.date.subtract(0, \'seconds\'));
            if(time === "00:00"){
              this.payment_set = false;
              this.select_bank = false;
              this.bank_id = null;
              this.date = moment(60 * 10 * 1000),
              this.payment={
                hours:null,
                time:null,
                remark:null
             }
             window.location.href="/mate-order/index"
           clearInterval(interval); 
          }
       }, 1000);
    }
    }
    });
');
?>