controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Address;
use app\models\Movement;
use app\models\Photos;
use app\models\Product;
use app\models\Profile;
use app\models\SignupForm;
use app\models\Types;
use app\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use kartik\widgets\Alert;
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'items-details', 'profile'],
                'rules' => [
                    [
                        'actions' => ['logout', 'items-details', 'profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest){
            if (!Profile::findOne(['user_id'=>Yii::$app->user->id])->full_name) {
                return $this->redirect(['site/profile?show=profile']);
            }
        }


        $search = Yii::$app->request->get('search');
        if (isset($search)) {
            $dataProvider = Yii::$app->db->createCommand("select * from product where name LIKE '%$search%' order by id desc ")->queryAll();

        } else {
            $dataProvider = Yii::$app->db->createCommand('select * from product where status = 1 order by id desc ')->queryAll();
        }

        foreach ($dataProvider as $k => &$model) {
            $model['photos'] = $dataPH = Photos::findOne(['product_id' => $model['id']]) ? Yii::getAlias('@web') . '/uploads/' . Photos::findOne(['product_id' => $model['id']])->name : '';
        }
        $product_type = Types::find()->where(['status' => 1])->asArray()->all();
        foreach ($product_type as $k => &$type) {
            $type['count'] = Product::find()->where(['types_id' => $type['id']])->count();
        }
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'product_type' => json_encode($product_type)
        ]);
    }
    public function actionConfirm($id,$token){
       $u= User::findOne($id);
        $u->status = 10;
        $u->save();
        $this->redirect(['login']);
    }
    public function actionItemsDetails($id)
    {
        $model = Product::find()->where(['id' => $id])->asArray()->all();
        foreach ($model as $k => &$models) {
            $models['photos'] = Photos::findOne(['product_id' => $models['id'], 'status_use' => 1]) ? Yii::getAlias('@web') . '/uploads/' . Photos::findOne(['product_id' => $models['id'], 'status_use' => 1])->name : '';
            $models['amount'] = Movement::find()->where(['product_id' => $models['id']])->sum('amount') ? Movement::find()->where(['product_id' => $models['id']])->sum('amount') : 0;
        }
        $product_list = Product::find()->where(['types_id' => Product::findOne(['id' => $id])->types_id])->asArray()->all();

        foreach ($product_list as $k => &$list) {
            $list['photos'] = Photos::findOne(['product_id' => $list['id'], 'status_use' => 1]) ? Yii::getAlias('@web') . '/uploads/' . Photos::findOne(['product_id' => $list['id'], 'status_use' => 1])->name : '';
        }
        $images = Photos::find()->where(['product_id' => $id])->asArray()->all();
        return $this->render('_item_product_details', [
            'model' => json_encode($model),
            'imagesList' => json_encode($images),
            'product_list' => json_encode($product_list)
        ]);
    }

    public function actionListCart()
    {
        $address = Address::findOne(['status' => 1, 'user_id' => Yii::$app->user->id]);
        return $this->render('_list_cart', ['address' => $address]);
    }

    public function actionSubCart()
    {
        return $this->renderPartial('subscribe_cart');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (!Profile::findOne(['user_id'=>User::findOne(['username'=>$model->username])->id])->full_name) {
                return $this->redirect(['site/profile?show=profile']);
            } else {
                return $this->goBack();

            }
        };
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {

            return $this->redirect(['login','id'=>'confirm']);
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionProfile()
    {
        $user_id = Yii::$app->user->id;
        $profile = Profile::findOne(['id' => $user_id]);
        if ($profile->load(Yii::$app->request->post())) {
            $profile->save();
            return $this->refresh();
        }
        return $this->render('profile', ['profile' => $profile]);
    }

    public function actionDeleteAddress($id)
    {
        Address::findOne(['id' => $id])->delete();
        return $this->redirect(['site/profile', 'show' => 'address']);
    }

    public function actionSetStatusAddress($id)
    {

        foreach (Address::findAll(['user_id' => Yii::$app->user->id]) as $model) {
            $model->status = null;
            $model->save();
        }
        $add = Address::findOne(['id' => $id]);
        $add->status = 1;
        $add->save();
        return $this->redirect(['site/profile', 'show' => 'address']);
    }
}

views/site/_address.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use app\models\Address;
$user_id = Yii::$app->user->id;
if($id = Yii::$app->request->get('id')){
    $model = Address::findOne(['id'=>$id]);
}else{
    $model = new Address();

}
if($model->load(Yii::$app->request->post()) ){
   $model->user_id= $user_id;
    $model->save();
     return  Url::to(['site/profile','show'=>'address']);
}
?>

<div class="text-right">



</div>
<div class="row">

    <div class="col-md-8">
        <h5>ที่อยู่ของฉัน</h5>
        <?php foreach (Address::find()->where(['user_id'=>$user_id])->orderBy('status') ->all()as $item ):?>
            <div class="box">
                <!-- itemside // -->
                <div class="itemside mb-3">
                    <div class="aside">
                        <i class="icon-xs bg-success rounded-circle fa fa-user white"></i>
                    </div>
                    <div class="info">
                        <small class="text-muted">ชื่อ-นามสกุล</small>
                        <p><?=$item->full_name?></p>
                    </div>
                </div>
                <div class="itemside  mb-3">
                    <div class="aside">
                        <i class="icon-xs bg-secondary rounded-circle fa fa-phone white"></i>
                    </div>
                    <div class="info">
                        <small class="text-muted">เบอร์โทร</small>
                        <p><?=$item->phone?></p>
                    </div>
                </div><!-- itemside // -->



                <div class="itemside">
                    <div class="aside">
                        <i class="icon-xs bg-danger rounded-circle fa fa-file white"></i>
                    </div>
                    <div class="info">
                        <small class="text-muted">ที่อยู่</small>
                        <p><?=$item->address?></p>
                    </div>
                </div><!-- itemside // -->

                <div class="text-right">
                    <a href="<?=Url::to(['site/profile','show'=>'address','id'=>$item->id])?>">  <span class="text-warning">แก้ไข</span> </a>
                    <?php if($item->status !=1):?>
                        <a href="<?=Url::to(['site/set-status-address','id'=>$item->id])?>"> <span class="text-info">ตั้งเป็นที่อยู่หลัก</span> </a>
                    <a href="<?=Url::to(['site/delete-address','id'=>$item->id])?>"><span class="text-danger">ลบ</span></a>
                    <?php endif;?>

                        <?php if($item->status ==1):?>
                            <div  disabled class="btn btn-sm btn-outline-success float-left"> <i class="fa fa-check"></i> ใช่้เป็นที่อยู่หลัก</div>
                        <?php endif;?>

                </div>
            </div> <!-- box.// -->
            <?php endforeach;?>
    </div>
    <div class="col-md-4">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'phone')->textInput(['maxlength' => 10]) ?>
        <?= $form->field($model, 'status')->checkbox(['maxlength' => true,'value'=>1])?>
        <?= $form->field($model, 'address')->textarea(['maxlength' => true,'rows'=>3]) ?>


        <div class="form-group">
            <?= Html::submitButton($id?'<span class="fa fa-edit"></span> แก้ไขที่อยู่':'<span class="fa fa-plus"></span> เพิ่มที่อยู่', ['class' => 'btn btn-outline-success btn-block']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/_item_product_details.php
<?php
$this->title = 'รายละเอียดสินค้า';
$id = Yii::$app->request->get('id');
if($id){
    $product =  \app\models\Product::findOne(['id'=>$id]);
    $product->view = $product->view+1;
    $product->save();
}
?>

    <section class="section-pagetop bg-gradient-orange  ">
        <div class="container">
            <h2 class="title-page"><?= \yii\helpers\Html::encode($this->title) ?></h2>
            <nav>
                <ol class="breadcrumb text-white">
                    <li class="breadcrumb-item "><a href="<?= Yii::$app->homeUrl ?>">หน้าหลัก</a></li>
                    <li class="breadcrumb-item active"
                        aria-current="page"><?= \yii\helpers\Html::encode($this->title) ?></li>
                </ol>
            </nav>
        </div>
    </section>
    <div class="container" id="app-details" v-cloak>
        <br>

        <div class="card" v-for="model in product_details">
            <div class="row no-gutters">
                <aside class="col-sm-5 border-right">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div><a :href="model.photos" data-fancybox=""><img :src="model.photos"></a></div>
                        </div> <!-- slider-product.// -->
                        <div class="img-small-wrap">
                            <div class="item-gallery" v-for="ph in photos_list">
                                <a :href="<?= Yii::getAlias('@web') . '/uploads/' ?>+ph.name" data-fancybox="">
                                    <img :src="<?= Yii::getAlias('@web') . '/uploads/' ?>+ph.name">
                                </a>
                            </div>
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <aside class="col-sm-7">
                    <article class="p-5">
                        <h3 class="title mb-3">{{model.name}}</h3>

                        <div class="mb-3">
                            <var class="price h3 text-warning">
                                <span class="currency"></span><span class="num">{{model.price}}</span>
                            </var>
                            <span>/บาท</span>
                        </div> <!-- price-detail-wrap .// -->


                        <div class="rating-wrap">
                            <div class="label-rating" v-if="model.view"> จำนวนดูสินค้า {{model.view}}</div>
                            <div class="label-rating">
                                <small class="label-rating text-success" v-if="model.amount">
                                    <i class="fa fa-clipboard-check"></i> จำนวน {{model.amount}} รายการ </small>

                                <span class="text-danger" v-else> สินค้าหมด </span>
                            </div>
                        </div> <!-- rating-wrap.// -->
                        <hr>
                        <div class="form-row">
                            <div class="form-group col-md flex-grow-0">
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                        <button class="btn btn-light" type="button" id="button-plus"
                                                @click="plusAmount(model)"> +
                                        </button>
                                    </div>
                                    <input type="text" class="form-control" v-model="amount_product">
                                    <div class="input-group-append">
                                        <button class="btn btn-light" type="button" id="button-minus"
                                                :disabled="amount_product==1" @click="amount_product--"> −
                                        </button>
                                    </div>
                                </div>  <!-- input-spinner.// -->
                            </div> <!-- col.// -->
                            <div class="form-group col-md">
                                <a href="#" class="btn  btn-outline-primary" v-if="model.amount" @click="addCart(model)"> <i
                                            class="fas fa-shopping-cart"></i> เพิ่มไปยังรถเข็น </a>
                                <a href="#" class="btn  btn-outline-success" @click="addCartPay(model)" v-if="model.amount"> <i
                                            class="fas fa-shopping-bag" ></i> ซื้อสินค้า </a>
                                <a href="<?=Yii::$app->homeUrl?>" class="btn  btn-outline-danger" v-else> <i class="fas fa-ban"></i>
                                    สินค้าหมด</a>
                            </div> <!-- col.// -->
                        </div> <!-- row.// -->

                        <hr>
                        <a href="#" class="title mt-2 h5">รายละเอียดสินค้า</a>
                        <dl style="width: ">
                            <dt></dt>
                            <dd><p v-html="model.details"></p></dd>
                        </dl>
                    </article> <!-- card-body.// -->
                </aside> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->

        <hr class="divider">

        <div class="card card-body">
            <h5>สินค้าคล้ายกัน</h5>
            <div class="row">
                <div class="col-md-3" v-for="model in product_list">
                    <figure class="itemside mb-4"  >
                        <div class="aside"><img :src="model.photos" class="img-sm"></div>
                        <figcaption class="info align-self-center info-wrap">
                            <p class="title" style=" /* or inline-block */
  text-overflow: ellipsis;
  word-wrap: break-word;
  overflow: hidden;
  max-height: 3.6em;
  line-height: 1.8em;">{{model.name}}</p>
                            <a href="#"  class="btn btn-outline-success btn-sm" @click="itemProductDetails(model.id)"> ซื้อสินค้า
                                <i class="fa fa-shopping-cart"></i>
                            </a>

                        </figcaption>
                    </figure>
                </div> <!-- col.// -->

            </div> <!-- row.// -->
        </div>
    </div>


<?php
$this->registerJs('
var csrfToken = $(\'meta[name = "csrf-token"]\').attr("content");
var app = new Vue({
    store,
  el: "#app-details",
  data: {
      product_details : '.$model.',
      photos_list :'.$imagesList.',
      amount_product:1,
      product_list:'.$product_list.',
  },
  computed: {
  
  },
   methods: {
      plusAmount(model){
        if(this.amount_product < model.amount ){
            this.amount_product ++;
        }
      },
      itemProductDetails(id){
           window.location.href="/site/items-details?id="+id;
      },
      addCart:function(item) {
      item["amount_set"] = this.amount_product;
          this.$store.commit("ADD_TO_CART", item);
      },
      addCartPay:function(item) {
      item["amount_set"] = this.amount_product;
          this.$store.commit("ADD_TO_CART", item);
            window.location.href="/site/list-cart"
      }
   }
     
})
'
);

?>

views/site/about.php
<?php
use yii\helpers\Html;
$this->title = 'เกี่ยวกับเรา';
?>
<div class="site-about">
    <?=Yii::$app->global->breadcrumbDisplay($this->title)?>

    <div class="container">
        <article class="card">
            <div class="card-body">
                <div class="row">
                    <aside class="col-md-6">
                        <h3>ร้าน<?=Yii::$app->name?></h3>
                        <dl class="row">
                            <dt class="col-sm-3">รับงานปั้นลอยตัว</dt>
                            <dd class="col-sm-9">13.3-inch LED-backlit display with IPS</dd>

                            <dt class="col-sm-3">งานปั้นโนนสูง</dt>
                            <dd class="col-sm-9">2.3GHz dual-core Intel Core i5</dd>

                            <dt class="col-sm-3">งานออกแบบปั้นต่างๆ</dt>
                            <dd class="col-sm-9">720p FaceTime HD camera</dd>

                            <dt class="col-sm-3">รับออกแบบตัวอักษร</dt>
                            <dd class="col-sm-9">8 GB RAM or 16 GB RAM</dd>

                            <dt class="col-sm-3">Graphics</dt>
                            <dd class="col-sm-9">Intel Iris Plus Graphics 640</dd>
                        </dl>
                    </aside>
                    <aside class="col-md-6">
                        <h3>ที่อยู่</h3>
                        <ul class="list-check">
                            <li>Best performance of battery</li>
                            <li>5 years warranty for this product</li>
                            <li>Amazing features and high quality</li>
                            <li>Best performance of battery</li>
                            <li>5 years warranty for this product</li>
                            <li>Amazing features and high quality</li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
                <hr>
                <h4>
                    ช่องทางติดต่อ
                </h4>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card" style="width:20rem;margin:20px 0 24px 0; height: 450px">
                            <img class="card-img-top text-center"  src="<?=Yii::getAlias('@web/app_frontend/images/line/call.jpeg')?>" alt="image" style="width:250px">
                            <div class="card-body text-center">
                                <h4 class="card-title text-success"></h4>
                                <a href="084-5486-806" class="btn btn-outline-success btn-block" ><i class="fa fa-phone"></i> 084-5486-806</a>
                                <a href="084-5486-806" class="btn btn-outline-success btn-block" > <i class="fa fa-phone"></i> 084-5486-806</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card" style="width:20rem;margin:20px 0 24px 0;height: 450px">
                            <img class="card-img-top" src="<?=Yii::getAlias('@web/app_frontend/images/line/10241.jpg')?>" alt="image" style="width:width:290px">
                            <div class="card-body text-center">
                                <h4 class="card-title text-success"></h4>
                                <a href="https://line.me/ti/p/Q_4rGTsu8j" class="btn btn-outline-primary btn-block">@เพิ่มเพื่อนเพิ่มคุยกับเรา</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- card-body.// -->
        </article>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'เข้าสู่ระบบ';
//$this->params['breadcrumbs'][] = $this->title;
$user = \app\models\User::findOne(['username'=>$model->username]);
?>
<?=Yii::$app->global->breadcrumbDisplay($this->title)?>
<div class="site-login" style="margin-top: 15px"  >
    <?php if($user):?>
        <?php if ($user->status ==9):?>

            <div class="alert alert-warning" role="alert">
                กรุณายืนยันข้อมูลผ่านอีเมล์ก่อน <span class="alert-link">เข้าสู่ระบบ</span>...
            </div>
        <?php endif;?>
    <?php endif;?>

    <?php if(Yii::$app->request->get('id')=='confirm'):?>
         <div class="alert alert-danger" role="alert">
                กรุณายืนยันข้อมูลผ่านอีเมล์ก่อน <span class="alert-link">เข้าสู่ระบบ</span>...
            </div>
    <?php endif;?>
<div class="row">

    <div class="col-sm-4 offset-4">
            <div class="card">
                <article class="card-body">
                    <a href="<?=\yii\helpers\Url::to(['site/signup'])?>" class="float-right btn btn-outline-success">สมัครสมาชิก</a>
                    <h4 class="card-title mb-4 mt-1"><?=\yii\helpers\Html::encode($this->title)?></h4>
                    <?php $form = ActiveForm::begin([
                        'id' => 'login-form',

                    ]); ?>
                        <div class="form-group">
                            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>
                        </div> <!-- form-group// -->
                        <div class="form-group">
                            <?= $form->field($model, 'password')->passwordInput() ?>
                        </div> <!-- form-group// -->
                        <div class="form-group">
                            <?= $form->field($model, 'rememberMe')->checkbox() ?>
                        </div> <!-- form-group// -->
                        <div class="form-group">
                            <?= Html::submitButton('เข้าสู่ระบบ', ['class' => 'btn btn-outline-primary btn-block', 'name' => 'login-button']) ?>
                        </div> <!-- form-group// -->
                    <?php ActiveForm::end(); ?>

                </article>
            </div> <!-- card.// -->
    </div>
</div>






</div>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'สมัครสมาชิก';
//$this->params['breadcrumbs'][] = $this->title;
?>
<?=Yii::$app->global->breadcrumbDisplay($this->title)?>
<div class="row">
    <div class="col-md-5 offset-3">
        <div class="card">
            <div class="card-body">
                <div class="site-signup">
                    <h1><?= Html::encode($this->title) ?></h1>

                            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                            <?= $form->field($model, 'email') ?>

                            <?= $form->field($model, 'password')->passwordInput() ?>

                            <div class="form-group">
                                <?= Html::submitButton('สมัครสมาชิก', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                            </div>

                            <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>